import { number, time } from 'framer-motion';

export const NAV_LINKS = [
    { name: 'Dashboard Overview', href: '/', image: '/home.png' },
    { name: 'Call Logs', href: '/call-logs', image: '/call.png' },
    { name: 'Appointments', href: '/appointments', image: '/calender.png' },
    { name: 'Settings', href: '/settings', image: '/setting.png' },
];

export const DASHBOARD_CARDS = [
    {
        name: 'Total Calls Today',
        value: '127',
        percentage: '12%',
        status: 'positive',
        image: '/call-color.png',
    },
    {
        name: 'Al-Handle Calls',
        value: '98',
        percentage: '77%',
        status: 'positive',
        image: '/handle-call.png',
    },
    {
        name: 'Warn Transfer',
        value: '23',
        percentage: '18%',
        status: 'positive',
        image: '/transfer.png',
    },
    {
        name: 'Appoinments Booked',
        value: '34',
        percentage: '8%',
        status: 'positive',
        image: '/appoinments.png',
    },
    {
        name: 'Missed/ Failed Calls',
        value: '6',
        percentage: '3%',
        status: 'negative',
        image: '/missed-call.png',
    },
    {
        name: 'Avg Call Duration',
        value: '3:42',
        percentage: '15%',
        status: 'positive',
        image: '/call-duratoin.png',
    },
];

export const CALL_LISTS = [
    {
        image: '/call-color.png',
        number: '+1 (555) 345-6789',
        date: '2025-12-16',
        time: '09:42 AM',
        statusText: 'AI Resolved',
        status: 'success',
        durationIcon: '/duration-icon.png',
        duration: '5:23',
        title: 'Quote Provided',
        titleStatusIcon: '/quote-icon.png',
        category: 'Screen',
    },
    {
        image: '/call-color.png',
        number: '+1 (555) 345-6789',
        date: '2025-12-16',
        time: '09:42 AM',
        statusText: 'Warm Transfer',
        status: 'warning',
        durationIcon: '/duration-icon.png',
        duration: '5:23',
        title: 'Escalated to technician',
        titleStatusIcon: '/quote-icon.png',
        category: 'Software',
    },
    {
        image: '/call-color.png',
        number: '+1 (555) 345-6789',
        date: '2025-12-16',
        time: '09:42 AM',
        statusText: 'Appointment',
        status: 'default',
        durationIcon: '/duration-icon.png',
        duration: '5:23',
        title: 'Appointment Booked',
        titleStatusIcon: '/quote-icon.png',
        category: 'Battery',
    },
    {
        image: '/call-color.png',
        number: '+1 (555) 345-6789',
        date: '2025-12-16',
        time: '09:42 AM',
        statusText: 'Droppped',
        status: 'alert',
        durationIcon: '/detail-icon.png',
        duration: '5:23',
        title: 'Call Dropped',
        titleStatusIcon: '/quote-icon.png',
        category: 'Unknown',
    },
    {
        image: '/call-color.png',
        number: '+1 (555) 345-6789',
        date: '2025-12-16',
        time: '09:42 AM',
        statusText: 'AI Resolved',
        status: 'success',
        durationIcon: '/duration-icon.png',
        duration: '5:23',
        title: 'Quote Provided',
        titleStatusIcon: '/quote-icon.png',
        category: 'Screen',
    },
];
