import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import HeroProvider from '@/providers/HeroProviders';
import Header from '@/components/layout/Header';
import CallServiceProvider from '@/contexts/CallServiceContext';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata = {
    title: 'Assessment For Frontend Developer',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <CallServiceProvider>
                    <HeroProvider>
                        <Header />
                        {children}
                    </HeroProvider>
                </CallServiceProvider>
            </body>
        </html>
    );
}
